import Head from 'next/head'
import Image from 'next/image'


import Header from '@/components/Header'
import Link from 'next/link'
import collage from "../images/front_collage.jpg"
import naturel from "../images/naturel.png"
import TextSpan from '@/components/TextSpan'



export default function Home() {

  const sentence = "Medical Pro".split("")
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header></Header>
			<div className="pt-20">
				<section className="py-20">
					<div className="flex items-center max-w-6xl gap-20 mx-auto  bg-white bg-opacity-50 font-serif  p-4 md:p-4 md:px-6 ">
						<article className="px-8 pb-2">
							<div className="w-full">
								{sentence.map((letter, index) => {
									return (
										<TextSpan key={index}>
											{letter === " " ? "\u00A0" : letter}
										</TextSpan>
									)
								})}{" "}
							</div>

							<p className="pb-5 pt-10 italic text-2xl uppercase">
								Sans chirurgie
							</p>
							<p className="italic pb-10 text-sm">Le naturel révolution</p>
							<Link href="/makeups">
								<button className=" text-slate-600 bg-blue-200 hover:bg-blue-600 font-bold hover:text-white py-2 px-4 rounded-full">
									En savoir plus
								</button>
							</Link>
						</article>
						<Image
							height={800}
							width={400}
							src={collage}
							className="object-fit"
						></Image>
					</div>
				</section>
				<section>
					<div>
						<Image src={naturel} className="object-fit naturel"></Image>
					</div>
				</section>
			</div>
		</>
	)
}
