import Head from 'next/head'
import Image from 'next/image'


import Header from '@/components/Header'
import Link from 'next/link'
import collage from "../images/front_collage.jpg"

import TextSpan from '@/components/TextSpan'
import Temoignages from '@/components/Temoignages'





export default function Home() {

  const sentence = "Medical Pro".split("")
  return (
		<>
			<Head>
				<title>MedicalPro</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header></Header>
			<div className="pt-20">
				<section className="h-full pt-40 min-h-screen bg-[url('../images/clinic.jpg')] bg-no-repeat bg-cover bg-center bg-opacity-50">
					<div className="flex  items-center max-w-6xl gap-10 mx-auto  bg-white bg-opacity-90 font-serif flex-col lg:flex-row  p-4 md:p-4 md:px-8 ">
						<article className="px-8 pb-2">
							<div className="w-full">
								{sentence.map((letter, index) => {
									return (
										<TextSpan key={index}>
											{letter === " " ? "\u00A0" : letter}
										</TextSpan>
									)
								})}{" "}
							</div>

							<p className="pb-5 pt-10 italic text-2xl uppercase">
								Sans chirurgie
							</p>
							<p className="italic pb-10 text-sm">Le naturel révolution</p>
							<Link href="/makeups">
								<button className=" text-slate-600 bg-blue-200 hover:bg-blue-600 font-bold hover:text-white py-2 px-4 rounded-full">
									En savoir plus
								</button>
							</Link>
						</article>
						<Image
							height={800}
							width={600}
							src={collage}
							className="object-fit w-100 lg:w-96 lg:object-contain rounded-2xl opacity-90"
							quality={70}
						></Image>
					</div>
				</section>
				<section className="mb-20 mt-40 relative  grid place-items-center max-w-6xl mx-auto">
					<div className="naturel-w flex overflow-hidden  font-Shadows opacity-70 italic text-blue-200">
						<span className="txt t1 whitespace-nowrap text-4xl ">
							New York - Paris - Tokyo - Espagne - &nbsp;
						</span>

						<span className="txt t2 whitespace-nowrap text-4xl ">
							New York - Paris - Tokyo - Espagne - &nbsp;
						</span>
						<span className="txt t2 whitespace-nowrap text-4xl ">
							New York - Paris - Tokyo - Espagne - &nbsp;
						</span>
						<span className="txt t2 whitespace-nowrap text-4xl ">
							New York - Paris - Tokyo - Espagne - &nbsp;
						</span>
					</div>
					<h1 class="absolute font-bold tracking-widest -bottom-8 py-4 px-8 text-blue-500 text-8xl text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-blue-200 drop-shadow-lg">
						Témoignages
					</h1>
				</section>
				<Temoignages></Temoignages>
			</div>
		</>
	)
}
